/// Flutter icons Extra
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ExtraIcons
///      fonts:
///       - asset: fonts/Extra.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ExtraIcons {
  ExtraIcons._();

  static const _kFontFam = 'ExtraIcons';

  static const IconData pin_outline = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData pin = const IconData(0xe801, fontFamily: _kFontFam);
}
